plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
  - us-east-2
keyed_groups:
  - key: tags.App
filters:
  tag:App: talo-polybot
  instance-state-name: running
compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
