name: Polybot Infrastructure Terraform Main

on:
  workflow_dispatch:
    inputs:
      us-east-1:
        description: 'N.Virginia (us-east-1)'
        required: false
        type: boolean
      us-east-2:
        description: 'Ohio (us-east-2)'
        required: false
        type: boolean
      country:
        required: true
        type: string
        default: US
      state:
        required: true
        type: string
        default: Virginia
      locality:
        required: true
        type: string
        default: Virginia Beach
      organization:
        required: true
        type: string
        default: Talo Polybot
      common_name:
        required: true
        type: string
        default: talo-polybot.int-devops.click

jobs:
  us-east-1:
    if: ${{ inputs.us-east-1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: us-east-1
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.US_EAST_1_TELEGRAM_TOKEN }}

  us-east-2:
    if: ${{ inputs.us-east-2 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: us-east-2
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.US_EAST_2_TELEGRAM_TOKEN }}
